server:
  port: 9004

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  web:
    resources:
      add-mappings: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
      auto-offset-reset: earliest
    template:
      default-topic: test

springdoc:
  api-docs:
    path: /api-docs